name: detekt

on: [pull_request_target]

env:
  JAVA_VERSION: 17
  GRADLE_VERSION: 8.2

permissions:
  pull-requests: write

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run detekt
        run: ./gradlew detekt

      - name: Comment via reviewdog (detekt SARIF)
        if: always()
        run: |
          FILE=app/build/reports/detekt/detekt.sarif
          if [ -f "$FILE" ]; then
            cat "$FILE" | reviewdog -f=sarif -reporter=github-pr-review -filter-mode=nofilter -tee -fail-on-error=false || true
          else
            echo "SARIF not found"
          fi
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
