name: Static code analysis

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "microsoft"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # ✅ detektは失敗させず、max-issues指定
      - name: Run detekt
        run: ./gradlew detekt || true

      - name: reviewdog report
        if: always()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f app/reports/detekt/detekt.xml ]; then
            set +e
            reviewdog -f=checkstyle \
                      -name="detekt" \
                      -reporter=github-pr-review \
                      -filter-mode=added \
                      -fail-on-error=false \
                      -tee < app/reports/detekt/detekt.xml
            echo "✅ reviewdog finished with code $?"
          else
            echo "⚠️ detekt.xml not found. Skipping reviewdog."
          fi
